name: Remove Ads

on:
  push:
    branches:
      - main

jobs:
  update-Ad-Free:
    runs-on: ubuntu-22.04  # Explicitly use ubuntu-22.04

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Git
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        run: |
          git config --global user.name "${GIT_USERNAME:-github-actions}"
          git config --global user.email "${GIT_EMAIL:-github-actions@github.com}"

      - name: Remove Ads
        run: |
          git fetch origin
          if git branch --list | grep -q 'Ad-Free'; then
            git checkout Ad-Free
            git pull origin Ad-Free
            git merge main --no-edit
          else
            git checkout -b Ad-Free
          fi

      - name: Remove first 9 lines from m.js
        run: |
          sed -i '1,9d' static/assets/js/m.js
  
      - name: Commit changes
        run: |
          git add static/assets/js/m.js
          if git diff --cached --exit-code; then
            echo "No changes to commit."
          else
            git commit -m "Remove specific JS code from m.js"
          fi

      - name: Push changes to Ad-Free branch
        run: |
          git push origin Ad-Free --force
