name: Publish image to Docker Hub
on:
  [workflow_dispatch]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # Step 1: Log in to the Container registry
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    # Step 2: Check out the code
    - uses: actions/checkout@v4

    # Step 3: Set Git user configuration
    - name: Configure Git user
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
    
    # Step 4: Build and push the Docker image
    - name: Build and push Docker image
      run: |
        IMAGE_NAME=ghcr.io/$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')/interstellar-docker
        docker build . -t $IMAGE_NAME
        docker push $IMAGE_NAME
