name: Publish image to Docker Hub
on:
  [workflow_dispatch]

jobs:

  docker:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ secrets.GIT_EMAIL }}"
      env:
        GIT_EMAIL: youremail@example.com  # Replace with your email or use a GitHub secret for privacy

    - name: Build and Push Docker Image
      run: |
        docker build . -t ghcr.io/$(echo ${{github.actor}} | tr '[:upper:]' '[:lower:]')/interstellar-docker;
        docker push ghcr.io/$(echo ${{github.actor}} | tr '[:upper:]' '[:lower:]')/interstellar-docker;
