name: Publish image to Docker Hub
on:
  [workflow_dispatch]

jobs:

  docker:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Log in to the Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ secrets.GIT_EMAIL }}"
      env:
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}  # Ensure this secret is defined in GitHub

    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME="ghcr.io/$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')/interstellar-docker"
        docker build . -t $IMAGE_NAME
        docker push $IMAGE_NAME
